// AUTO-GENERATED by scripts/generate-icon-map.ts — do not edit by hand.
// Maps animation slug -> bundled 1024x1024 icon asset. Missing slugs fall back
// to the placeholder in icon-source.ts.
import type { ImageSourcePropType } from 'react-native';

export const ICON_MAP: Record<string, ImageSourcePropType> = {};
