/* eslint-disable no-console */
// Codegen: downscale the icon masters in assets/app-icons-src/*.png into the
// bundled assets/app-icons/, and emit a static require() map keyed by slug.
// Metro can't dynamic-require a runtime path, so the home grid resolves icons
// through this generated map (see src/navigation/home/icon-source.ts).
// Drop a `<slug>.png` (1024×1024) into assets/app-icons-src/, re-run this,
// reload.
//
//   bun scripts/generate-icon-map.ts
//
// Why two folders: the grid shows an icon at 62pt at most (186px at 3x), and
// that is the largest bitmap it ever draws: expo-image shrinks whatever it
// decodes to the view's own size, and the launch carries the icon by a
// transform, so a larger master only cost a bigger decode and a resize on the
// main thread for every icon that mounted (both showed in the home's traces,
// and a cold cache showed blank tiles while they ran). 192px is the view's
// size and a little over, so the views draw it as it is (`allowDownscaling`
// is off on them).
//
// `_placeholder.png` is excluded from the map — it's the fallback for any
// missing slug — but it is downscaled like the rest.
import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'assets/app-icons-src');
const ICONS_DIR = path.join(ROOT, 'assets/app-icons');
const OUT = path.join(ROOT, 'src/navigation/home/icon-map.generated.ts');
const BUNDLED_SIZE = 192;

fs.mkdirSync(ICONS_DIR, { recursive: true });
const sources = fs.readdirSync(SRC_DIR).filter(f => f.endsWith('.png'));
let resized = 0;
for (const file of sources) {
  const from = path.join(SRC_DIR, file);
  const to = path.join(ICONS_DIR, file);
  if (fs.existsSync(to) && fs.statSync(to).mtimeMs >= fs.statSync(from).mtimeMs)
    continue;
  // sips ships with macOS; -Z fits the longest edge, keeping the square.
  execFileSync('sips', ['-Z', String(BUNDLED_SIZE), from, '--out', to], {
    stdio: 'ignore',
  });
  resized++;
}
// A master that was removed takes its bundled copy with it.
for (const file of fs.readdirSync(ICONS_DIR)) {
  if (!sources.includes(file)) fs.rmSync(path.join(ICONS_DIR, file));
}

const slugs = sources
  .filter(f => f !== '_placeholder.png')
  .map(f => f.replace(/\.png$/, ''))
  .sort();

const lines = slugs.map(
  s => `  '${s}': require('../../../assets/app-icons/${s}.png'),`,
);

const inner = lines.length ? `\n${lines.join('\n')}\n` : '';
const body = `// AUTO-GENERATED by scripts/generate-icon-map.ts — do not edit by hand.
// Maps animation slug -> bundled ${BUNDLED_SIZE}x${BUNDLED_SIZE} icon asset (downscaled
// from assets/app-icons-src). Missing slugs fall back to the placeholder in
// icon-source.ts.
import type { ImageSourcePropType } from 'react-native';

export const ICON_MAP: Record<string, ImageSourcePropType> = {${inner}};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log(
  `icon-map.generated.ts: ${slugs.length} real icon(s) mapped, ${resized} downscaled.`,
);
