/* eslint-disable no-console */
// Codegen: derive each demo's backdrop colour from its app icon and emit a
// static slug -> #rrggbb map (src/navigation/home/icon-colors.generated.ts).
//
// The open-zoom card (open-zoom.tsx) and the demo screen's pre-mount
// placeholder (launcher.tsx) are flat colour surfaces that expand from the
// tapped icon to fullscreen. A fixed white reads wrong for dark demos, so we
// colour them per demo. The icon is a thumbnail of the demo itself, and its
// BORDER pixels are almost always the demo's background (the subject sits in
// the middle) — so the average of the icon's outer ring is a solid proxy for
// "the colour this demo's screen opens on".
//
//   bun scripts/generate-icon-colors.ts
//
// Requires ImageMagick (`magick`). Icons without a real asset fall back to
// white at runtime (see icon-source.ts).
import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const ICONS_DIR = path.join(ROOT, 'assets/app-icons');
const OUT = path.join(ROOT, 'src/navigation/home/icon-colors.generated.ts');

// Downsample size: the border ring of the NxN thumbnail is what we average.
const N = 16;

const slugs = fs
  .readdirSync(ICONS_DIR)
  .filter(f => f.endsWith('.png') && f !== '_placeholder.png')
  .map(f => f.replace(/\.png$/, ''))
  .sort();

const borderColor = (file: string): string => {
  // `txt:-` prints one line per pixel: "x,y: (r,g,b,a) #RRGGBBAA srgba(...)".
  const txt = execFileSync(
    'magick',
    [file, '-resize', `${N}x${N}!`, '-depth', '8', 'txt:-'],
    { encoding: 'utf8' },
  );
  let r = 0;
  let g = 0;
  let b = 0;
  let count = 0;
  for (const line of txt.split('\n')) {
    const m = line.match(/^(\d+),(\d+):\s*\((\d+),(\d+),(\d+)/);
    if (!m) continue;
    const x = Number(m[1]);
    const y = Number(m[2]);
    // Outer ring only — the icon's edge, i.e. the demo's background.
    if (x > 0 && x < N - 1 && y > 0 && y < N - 1) continue;
    r += Number(m[3]);
    g += Number(m[4]);
    b += Number(m[5]);
    count += 1;
  }
  if (!count) return '#ffffff';
  const hex = (v: number) =>
    Math.round(v / count)
      .toString(16)
      .padStart(2, '0');
  return `#${hex(r)}${hex(g)}${hex(b)}`;
};

const lines = slugs.map(s => {
  const color = borderColor(path.join(ICONS_DIR, `${s}.png`));
  return `  '${s}': '${color}',`;
});

const inner = lines.length ? `\n${lines.join('\n')}\n` : '';
const body = `// AUTO-GENERATED by scripts/generate-icon-colors.ts — do not edit by hand.
// Average colour of each icon's border ring: the flat backdrop the demo's
// open-zoom card expands with (and the pre-mount placeholder behind it).
export const ICON_COLORS: Record<string, string> = {${inner}};
`;

fs.writeFileSync(OUT, body);
console.log(`icon-colors.generated.ts: ${slugs.length} colour(s) mapped.`);
