/* eslint-disable no-console */
// Codegen: scan assets/app-icons/*.png and emit a static require() map keyed by
// slug. Metro can't dynamic-require a runtime path, so the home grid resolves
// icons through this generated map (see src/navigation/home/icon-source.ts).
// Drop a `<slug>.png` (1024×1024) into assets/app-icons/, re-run this, reload.
//
//   bun scripts/generate-icon-map.ts
//
// `_placeholder.png` is excluded — it's the fallback for any missing slug.
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const ICONS_DIR = path.join(ROOT, 'assets/app-icons');
const OUT = path.join(ROOT, 'src/navigation/home/icon-map.generated.ts');

const slugs = fs
  .readdirSync(ICONS_DIR)
  .filter(f => f.endsWith('.png') && f !== '_placeholder.png')
  .map(f => f.replace(/\.png$/, ''))
  .sort();

const lines = slugs.map(
  s => `  '${s}': require('../../../assets/app-icons/${s}.png'),`,
);

const inner = lines.length ? `\n${lines.join('\n')}\n` : '';
const body = `// AUTO-GENERATED by scripts/generate-icon-map.ts — do not edit by hand.
// Maps animation slug -> bundled 1024x1024 icon asset. Missing slugs fall back
// to the placeholder in icon-source.ts.
import type { ImageSourcePropType } from 'react-native';

export const ICON_MAP: Record<string, ImageSourcePropType> = {${inner}};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log(`icon-map.generated.ts: ${slugs.length} real icon(s) mapped.`);
